// Package loyalty manages the Whisked steeps program — earning steeps from
// in-bar purchases and Shopify orders, and redeeming rewards at milestones.
//
// The loyalty ledger is event-sourced: every earn and redemption is an
// immutable row in loyalty_events. The current balance is always derived
// from the event log, never stored in a mutable counter. This means:
//   - The full audit trail is always available
//   - The ledger can be replayed or recomputed at any time
//   - Retroactive reward tier changes don't require data migrations
//
// Idempotency is enforced at two layers:
//   1. Redis SET NX EX — fast path, prevents the DB roundtrip on retries
//   2. loyalty_events.idempotency_key UNIQUE — backstop if Redis is unavailable
package loyalty

import (
	"time"

	"github.com/q04-oss/whisked-platform/internal/platform"
)

// SteepsPerReward is the number of steeps required to earn one free drink.
const SteepsPerReward = 9

// EarnParams carries the inputs for recording a steep earn.
type EarnParams struct {
	CustomerID     platform.CustomerID
	Source         string // "in_bar" | "shopify"
	LocationID     *platform.LocationID
	ShopifyOrderID *platform.ShopifyOrderID
	// IdempotencyKey must be a UUID generated by the client. It prevents
	// duplicate steeps from network retries or app bugs.
	IdempotencyKey string
}

// Balance is the derived loyalty state for a customer.
// Computed from the event log on every read.
type Balance struct {
	CustomerID      platform.CustomerID `json:"customer_id"`
	SteepsEarned    int64               `json:"steeps_earned"`
	RewardsRedeemed int64               `json:"rewards_redeemed"`
	// Available is the number of free drinks the customer can redeem right now.
	Available int64 `json:"available_rewards"`
	// Progress is how many steeps the customer has accumulated toward the next reward.
	Progress int64 `json:"steeps_progress"`
	// Until is how many more steeps are needed to earn the next reward.
	Until int64 `json:"steeps_until_next"`
}

// Event is a single entry in the loyalty history returned to clients.
type Event struct {
	ID         platform.LoyaltyEventID `json:"id"`
	EventType  string                  `json:"event_type"`
	Source     string                  `json:"source"`
	LocationID *platform.LocationID    `json:"location_id,omitempty"`
	CreatedAt  time.Time               `json:"created_at"`
}

// computeBalance derives a Balance from raw event counts.
func computeBalance(customerID platform.CustomerID, steepsEarned, rewardsRedeemed int64) Balance {
	totalRewardsEarned := steepsEarned / SteepsPerReward
	available := totalRewardsEarned - rewardsRedeemed
	if available < 0 {
		available = 0
	}
	progress := steepsEarned % SteepsPerReward
	until := int64(SteepsPerReward) - progress

	return Balance{
		CustomerID:      customerID,
		SteepsEarned:    steepsEarned,
		RewardsRedeemed: rewardsRedeemed,
		Available:       available,
		Progress:        progress,
		Until:           until,
	}
}
